name: Daily Faceless TikTok
permissions:
  contents: write # FIX: Grants permission to push videos/index.html back to repo

on:
  schedule:
    # FIX: 3 Posts Per Day (Times are in UTC: 4 AM, 12 PM, 8 PM)
    - cron: '0 4,12,20 * * *' 
  workflow_dispatch: # Allows manual trigger for testing

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg imagemagick google-chrome-stable
          # FIX: Essential for MoviePy text rendering in 2026
          sudo sed -i 's/none/read,write/g' /etc/ImageMagick-6/policy.xml

      - name: Install Python Deps
        run: |
          pip install google-genai moviepy tiktok-uploader playwright edge-tts
          playwright install chromium --with-deps

      - name: Create Cookie File
        env:
          COOKIE_DATA: ${{ secrets.TIKTOK_COOKIES }}
        run: echo "$COOKIE_DATA" > cookies.txt

      - name: Run Bot
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python main.py

      - name: Commit and Push Video & Logs
        run: |
          git config --global user.name "TikTok-Bot"
          git config --global user.email "bot@github.com"
          git add .
          # Only commit if there are changes to avoid workflow errors
          git diff --quiet && git diff --staged --quiet || (git commit -m "New video & dashboard update: $(date)" && git push)
