name: Daily Faceless TikTok
on:
  schedule:
    - cron: '0 12 * * *' # Every day at noon
  workflow_dispatch:      # Allows you to test manually from the GitHub UI

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg imagemagick
          # CRITICAL: Fix ImageMagick security policy to allow font rendering
          sudo sed -i 's/none/read,write/g' /etc/ImageMagick-6/policy.xml

      - name: Install Python Deps
        run: |
          # Added edge-tts to the installation list
          pip install google-genai moviepy tiktok-uploader playwright edge-tts
          playwright install chromium --with-deps

      - name: Decode Cookies
        env:
          COOKIE_DATA: ${{ secrets.TIKTOK_COOKIES }}
        run: echo "$COOKIE_DATA" > cookies.txt

      - name: Run Bot
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python main.py
