name: Daily YouTube Shorts Automation
permissions:
  contents: write

on:
  schedule:
    - cron: '0 4,12,20 * * *' # 3 Posts per day
  push:
    branches:
      - main              # TRIGGER: Runs whenever you push a new commit
  workflow_dispatch:      # Manual trigger

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg imagemagick google-chrome-stable
          sudo sed -i 's/none/read,write/g' /etc/ImageMagick-6/policy.xml

      - name: Install Python Deps
        run: |
          pip install google-genai moviepy youtube-up playwright edge-tts
          playwright install chromium --with-deps

      - name: Decode YouTube Cookies
        env:
          YT_B64: ${{ secrets.YT_COOKIES_B64 }}
        run: echo "$YT_B64" | base64 --decode > youtube_cookies.json

      - name: Run Bot
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python main.py

      - name: Commit and Push Video & Dashboard
        run: |
          git config --global user.name "YouTube-Shorts-Bot"
          git config --global user.email "bot@github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "New Short & Gallery update: $(date)" && git push)
